# Form implementation generated from reading ui file 'src/UI/UI.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1080, 720)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.show_csv = QtWidgets.QPushButton(parent=self.centralwidget)
        self.show_csv.setGeometry(QtCore.QRect(910, 20, 111, 51))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("src/UI/docs.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.show_csv.setIcon(icon)
        self.show_csv.setIconSize(QtCore.QSize(32, 32))
        self.show_csv.setObjectName("show_csv")
        self.show_path = QtWidgets.QLabel(parent=self.centralwidget)
        self.show_path.setGeometry(QtCore.QRect(30, 20, 731, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.show_path.setFont(font)
        self.show_path.setFrameShape(QtWidgets.QFrame.Shape.Box)
        self.show_path.setObjectName("show_path")
        self.select_file = QtWidgets.QPushButton(parent=self.centralwidget)
        self.select_file.setGeometry(QtCore.QRect(790, 20, 111, 51))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("src/UI/folder.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.select_file.setIcon(icon1)
        self.select_file.setIconSize(QtCore.QSize(32, 32))
        self.select_file.setObjectName("select_file")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.show_csv.setText(_translate("MainWindow", "預測成果"))
        self.show_path.setText(_translate("MainWindow", "Select target video..."))
        self.select_file.setText(_translate("MainWindow", "選擇檔案"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
