# Form implementation generated from reading ui file 'UI.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1080, 720)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setAnimated(False)
        MainWindow.setDocumentMode(False)
        MainWindow.setTabShape(QtWidgets.QTabWidget.TabShape.Rounded)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.show_path = QtWidgets.QTextBrowser(parent=self.centralwidget)
        self.show_path.setGeometry(QtCore.QRect(10, 10, 854, 51))
        font = QtGui.QFont()
        font.setFamily(".AppleSystemUIFont")
        font.setPointSize(14)
        self.show_path.setFont(font)
        self.show_path.setAutoFillBackground(False)
        self.show_path.setStyleSheet("background:rgb(230, 230, 230);\n"
"color: rgb(30, 30, 30);\n"
"border-radius: 10px;\n"
"border-style: outset;\n"
"")
        self.show_path.setFrameShape(QtWidgets.QFrame.Shape.Box)
        self.show_path.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.show_path.setAutoFormatting(QtWidgets.QTextEdit.AutoFormattingFlag.AutoBulletList)
        self.show_path.setObjectName("show_path")
        self.show_analysis = QtWidgets.QLabel(parent=self.centralwidget)
        self.show_analysis.setGeometry(QtCore.QRect(10, 600, 854, 81))
        self.show_analysis.setStyleSheet("border-radius: 10px;\n"
"border-style: outset;\n"
"border-width: 1px;\n"
"border-color: rgb(128, 128, 128);")
        self.show_analysis.setFrameShape(QtWidgets.QFrame.Shape.Box)
        self.show_analysis.setText("")
        self.show_analysis.setObjectName("show_analysis")
        self.groupBox = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.groupBox.setEnabled(True)
        self.groupBox.setGeometry(QtCore.QRect(870, 70, 201, 611))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.groupBox.setFont(font)
        self.groupBox.setStyleSheet("border-radius: 10px;\n"
"background:rgb(230, 230, 230);\n"
"color: rgb(30, 30, 30);")
        self.groupBox.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.groupBox.setFlat(False)
        self.groupBox.setObjectName("groupBox")
        self.radioButton_2 = QtWidgets.QRadioButton(parent=self.groupBox)
        self.radioButton_2.setGeometry(QtCore.QRect(5, 90, 150, 21))
        self.radioButton_2.setObjectName("radioButton_2")
        self.radioButton_5 = QtWidgets.QRadioButton(parent=self.groupBox)
        self.radioButton_5.setGeometry(QtCore.QRect(5, 270, 150, 21))
        self.radioButton_5.setObjectName("radioButton_5")
        self.radioButton_3 = QtWidgets.QRadioButton(parent=self.groupBox)
        self.radioButton_3.setGeometry(QtCore.QRect(5, 150, 150, 21))
        self.radioButton_3.setObjectName("radioButton_3")
        self.radioButton_9 = QtWidgets.QRadioButton(parent=self.groupBox)
        self.radioButton_9.setGeometry(QtCore.QRect(5, 510, 150, 21))
        self.radioButton_9.setObjectName("radioButton_9")
        self.radioButton_7 = QtWidgets.QRadioButton(parent=self.groupBox)
        self.radioButton_7.setGeometry(QtCore.QRect(5, 390, 150, 21))
        self.radioButton_7.setObjectName("radioButton_7")
        self.radioButton_4 = QtWidgets.QRadioButton(parent=self.groupBox)
        self.radioButton_4.setGeometry(QtCore.QRect(5, 210, 150, 21))
        self.radioButton_4.setObjectName("radioButton_4")
        self.radioButton_6 = QtWidgets.QRadioButton(parent=self.groupBox)
        self.radioButton_6.setGeometry(QtCore.QRect(5, 330, 150, 21))
        self.radioButton_6.setObjectName("radioButton_6")
        self.radioButton_10 = QtWidgets.QRadioButton(parent=self.groupBox)
        self.radioButton_10.setGeometry(QtCore.QRect(5, 570, 150, 21))
        self.radioButton_10.setObjectName("radioButton_10")
        self.radioButton_1 = QtWidgets.QRadioButton(parent=self.groupBox)
        self.radioButton_1.setGeometry(QtCore.QRect(5, 30, 150, 21))
        self.radioButton_1.setObjectName("radioButton_1")
        self.radioButton_8 = QtWidgets.QRadioButton(parent=self.groupBox)
        self.radioButton_8.setGeometry(QtCore.QRect(5, 450, 150, 21))
        self.radioButton_8.setObjectName("radioButton_8")
        self.gif_1 = QtWidgets.QLabel(parent=self.groupBox)
        self.gif_1.setGeometry(QtCore.QRect(165, 25, 30, 30))
        self.gif_1.setFrameShape(QtWidgets.QFrame.Shape.Box)
        self.gif_1.setText("")
        self.gif_1.setObjectName("gif_1")
        self.gif_2 = QtWidgets.QLabel(parent=self.groupBox)
        self.gif_2.setGeometry(QtCore.QRect(165, 85, 30, 30))
        self.gif_2.setFrameShape(QtWidgets.QFrame.Shape.Box)
        self.gif_2.setText("")
        self.gif_2.setObjectName("gif_2")
        self.gif_3 = QtWidgets.QLabel(parent=self.groupBox)
        self.gif_3.setGeometry(QtCore.QRect(165, 145, 30, 30))
        self.gif_3.setFrameShape(QtWidgets.QFrame.Shape.Box)
        self.gif_3.setText("")
        self.gif_3.setObjectName("gif_3")
        self.gif_4 = QtWidgets.QLabel(parent=self.groupBox)
        self.gif_4.setGeometry(QtCore.QRect(165, 205, 30, 30))
        self.gif_4.setFrameShape(QtWidgets.QFrame.Shape.Box)
        self.gif_4.setText("")
        self.gif_4.setObjectName("gif_4")
        self.gif_5 = QtWidgets.QLabel(parent=self.groupBox)
        self.gif_5.setGeometry(QtCore.QRect(165, 265, 30, 30))
        self.gif_5.setFrameShape(QtWidgets.QFrame.Shape.Box)
        self.gif_5.setText("")
        self.gif_5.setObjectName("gif_5")
        self.gif_6 = QtWidgets.QLabel(parent=self.groupBox)
        self.gif_6.setGeometry(QtCore.QRect(165, 325, 30, 30))
        self.gif_6.setFrameShape(QtWidgets.QFrame.Shape.Box)
        self.gif_6.setText("")
        self.gif_6.setObjectName("gif_6")
        self.gif_7 = QtWidgets.QLabel(parent=self.groupBox)
        self.gif_7.setGeometry(QtCore.QRect(165, 385, 30, 30))
        self.gif_7.setFrameShape(QtWidgets.QFrame.Shape.Box)
        self.gif_7.setText("")
        self.gif_7.setObjectName("gif_7")
        self.gif_8 = QtWidgets.QLabel(parent=self.groupBox)
        self.gif_8.setGeometry(QtCore.QRect(165, 445, 30, 30))
        self.gif_8.setFrameShape(QtWidgets.QFrame.Shape.Box)
        self.gif_8.setText("")
        self.gif_8.setObjectName("gif_8")
        self.gif_9 = QtWidgets.QLabel(parent=self.groupBox)
        self.gif_9.setGeometry(QtCore.QRect(165, 505, 30, 30))
        self.gif_9.setFrameShape(QtWidgets.QFrame.Shape.Box)
        self.gif_9.setText("")
        self.gif_9.setObjectName("gif_9")
        self.gif_10 = QtWidgets.QLabel(parent=self.groupBox)
        self.gif_10.setGeometry(QtCore.QRect(165, 565, 30, 30))
        self.gif_10.setFrameShape(QtWidgets.QFrame.Shape.Box)
        self.gif_10.setText("")
        self.gif_10.setObjectName("gif_10")
        self.select_file = QtWidgets.QPushButton(parent=self.centralwidget)
        self.select_file.setGeometry(QtCore.QRect(870, 10, 101, 51))
        self.select_file.setStyleSheet("background:rgb(230, 230, 230);\n"
"border-radius: 10px; \n"
"border-style: outset;\n"
"border-color: black; \n"
"color: rgb(30, 30, 30);\n"
"border-top-right-radius: 0px;\n"
"border-bottom-right-radius: 0px;\n"
"\n"
"")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("folder.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.select_file.setIcon(icon)
        self.select_file.setIconSize(QtCore.QSize(24, 32))
        self.select_file.setObjectName("select_file")
        self.show_csv = QtWidgets.QPushButton(parent=self.centralwidget)
        self.show_csv.setGeometry(QtCore.QRect(970, 10, 101, 51))
        self.show_csv.setStyleSheet("border-radius: 10px; \n"
"border-style: outset;\n"
"background:rgb(230, 230, 230);\n"
"border-top-left-radius: 0px;\n"
"border-bottom-left-radius: 0px;\n"
"color: rgb(30, 30, 30);")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("docs.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.show_csv.setIcon(icon1)
        self.show_csv.setIconSize(QtCore.QSize(24, 24))
        self.show_csv.setAutoDefault(False)
        self.show_csv.setDefault(False)
        self.show_csv.setFlat(False)
        self.show_csv.setObjectName("show_csv")
        self.show_video = QtWidgets.QLabel(parent=self.centralwidget)
        self.show_video.setGeometry(QtCore.QRect(10, 70, 854, 480))
        self.show_video.setStyleSheet("border-radius: 10px;\n"
"border-style: outset;\n"
"border-width: 1px;\n"
"border-color: rgb(128, 128, 128);")
        self.show_video.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.show_video.setText("")
        self.show_video.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.show_video.setObjectName("show_video")
        self.play_pause = QtWidgets.QPushButton(parent=self.centralwidget)
        self.play_pause.setGeometry(QtCore.QRect(6, 549, 68, 50))
        self.play_pause.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("play-button.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.play_pause.setIcon(icon2)
        self.play_pause.setIconSize(QtCore.QSize(35, 35))
        self.play_pause.setAutoDefault(True)
        self.play_pause.setDefault(False)
        self.play_pause.setFlat(True)
        self.play_pause.setObjectName("play_pause")
        self.video_time = QtWidgets.QLabel(parent=self.centralwidget)
        self.video_time.setGeometry(QtCore.QRect(819, 550, 36, 50))
        self.video_time.setObjectName("video_time")
        self.slider = QtWidgets.QSlider(parent=self.centralwidget)
        self.slider.setGeometry(QtCore.QRect(80, 565, 733, 25))
        self.slider.setTracking(True)
        self.slider.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.slider.setTickPosition(QtWidgets.QSlider.TickPosition.NoTicks)
        self.slider.setObjectName("slider")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.show_path.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'.AppleSystemUIFont\'; font-size:14pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Select a target video...</p></body></html>"))
        self.groupBox.setTitle(_translate("MainWindow", "Video Box"))
        self.radioButton_2.setText(_translate("MainWindow", "RadioButton"))
        self.radioButton_5.setText(_translate("MainWindow", "RadioButton"))
        self.radioButton_3.setText(_translate("MainWindow", "RadioButton"))
        self.radioButton_9.setText(_translate("MainWindow", "RadioButton"))
        self.radioButton_7.setText(_translate("MainWindow", "RadioButton"))
        self.radioButton_4.setText(_translate("MainWindow", "RadioButton"))
        self.radioButton_6.setText(_translate("MainWindow", "RadioButton"))
        self.radioButton_10.setText(_translate("MainWindow", "RadioButton"))
        self.radioButton_1.setText(_translate("MainWindow", "RadioButton"))
        self.radioButton_8.setText(_translate("MainWindow", "RadioButton"))
        self.select_file.setText(_translate("MainWindow", "選擇檔案"))
        self.show_csv.setText(_translate("MainWindow", "預測成果"))
        self.video_time.setText(_translate("MainWindow", "00:00"))
