# Form implementation generated from reading ui file 'UI.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1080, 720)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setDocumentMode(False)
        MainWindow.setTabShape(QtWidgets.QTabWidget.TabShape.Rounded)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.show_path = QtWidgets.QTextBrowser(parent=self.centralwidget)
        self.show_path.setGeometry(QtCore.QRect(10, 10, 854, 51))
        font = QtGui.QFont()
        font.setFamily(".AppleSystemUIFont")
        font.setPointSize(14)
        self.show_path.setFont(font)
        self.show_path.setAutoFillBackground(False)
        self.show_path.setStyleSheet("background:rgb(220, 220, 220)")
        self.show_path.setFrameShape(QtWidgets.QFrame.Shape.Box)
        self.show_path.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.show_path.setAutoFormatting(QtWidgets.QTextEdit.AutoFormattingFlag.AutoBulletList)
        self.show_path.setObjectName("show_path")
        self.show_video = QtWidgets.QLabel(parent=self.centralwidget)
        self.show_video.setGeometry(QtCore.QRect(10, 70, 854, 480))
        self.show_video.setFrameShape(QtWidgets.QFrame.Shape.Box)
        self.show_video.setText("")
        self.show_video.setObjectName("show_video")
        self.show_analysis = QtWidgets.QLabel(parent=self.centralwidget)
        self.show_analysis.setGeometry(QtCore.QRect(10, 600, 854, 81))
        self.show_analysis.setFrameShape(QtWidgets.QFrame.Shape.Box)
        self.show_analysis.setText("")
        self.show_analysis.setObjectName("show_analysis")
        self.horizontalLayoutWidget = QtWidgets.QWidget(parent=self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 556, 851, 41))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(10, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.play = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget)
        self.play.setObjectName("play")
        self.horizontalLayout.addWidget(self.play)
        self.pause = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget)
        self.pause.setObjectName("pause")
        self.horizontalLayout.addWidget(self.pause)
        self.slider = QtWidgets.QSlider(parent=self.horizontalLayoutWidget)
        self.slider.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.slider.setObjectName("slider")
        self.horizontalLayout.addWidget(self.slider)
        self.video_time = QtWidgets.QLabel(parent=self.horizontalLayoutWidget)
        self.video_time.setObjectName("video_time")
        self.horizontalLayout.addWidget(self.video_time)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(parent=self.centralwidget)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(870, 10, 201, 51))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.select_file = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget_2)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("src/UI/folder.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.select_file.setIcon(icon)
        self.select_file.setIconSize(QtCore.QSize(24, 32))
        self.select_file.setObjectName("select_file")
        self.horizontalLayout_2.addWidget(self.select_file)
        self.show_csv = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget_2)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("src/UI/docs.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.show_csv.setIcon(icon1)
        self.show_csv.setIconSize(QtCore.QSize(24, 32))
        self.show_csv.setObjectName("show_csv")
        self.horizontalLayout_2.addWidget(self.show_csv)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.show_path.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'.AppleSystemUIFont\'; font-size:14pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Select a target video...</p></body></html>"))
        self.play.setText(_translate("MainWindow", "Play"))
        self.pause.setText(_translate("MainWindow", "Pause"))
        self.video_time.setText(_translate("MainWindow", "00:00"))
        self.select_file.setText(_translate("MainWindow", "選擇檔案"))
        self.show_csv.setText(_translate("MainWindow", "預測成果"))
